# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c08d6e6374a51c4479a32a26d619d840a493976c08522a9408e5a59dcbbd5c7851bd5f17667c744c507a9df121d5b9f4d9e71b1d24451fbad33dd847f79620ae

test:
  secret_key_base: dff099ebaab17656abd522ab00c9660c0c0840988d2d6455714beb46d30d6ca523400c118464158433d79334ecbbb5d23ae9f51b86d3f09808b7105d2a0f8e6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
